### ISSUE TITLE
Is there an official API dump?

### ISSUE THREAD

**Issue by ghost** [TorqueGameEngines/OnlineDocs#1]

**Comment by Azaezel** [comment]
Not at this point in time, but if you check https://github.com/TorqueGameEngines/Torque3D/blob/development/Engine/source/console/consoleDoc.cpp#L44-L60 you'll see a pair of `dumpConsoleClasses()` and `dumpConsoleFunctions()` methods to gen them for your version, 
We also recently integrated 
https://user-images.githubusercontent.com/4236451/224592269-c2d26415-0846-4531-9e14-96c6812fc53b.mp4
for a breadcrumb. on top of `%someobj.dump(); and we're refining a `%someobj.getMethodSigs()` we may use down the line for additional visual presentation/design tooling.

**Comment by ghost** [comment]
The `dump` method has seemed to be a good workaround for quite a bit. That, and I can simply dump the classes and use my best judgment from there.
